# Generated by Django 4.2 on 2026-06-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
